# -*- coding: utf-8 -*-
"""deleteMail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EfAaoGqBdMe08gvDSxBguQ-DjwRTdoDO
"""

# account credentials
username = "youremail@gmailcom"
password = "yourpassword"

# create an IMAP4 class with SSL 
imap = imaplib.IMAP4_SSL("imap.gmail.com")
# authenticate
imap.login(username, password)

imap.list()

import imaplib

my_email = "yourmail@gmail.com"
app_generated_password = "your password!"

#initialize IMAP object for Gmail
imap = imaplib.IMAP4_SSL("imap.gmail.com")

#login to gmail with credentials
imap.login(my_email, app_generated_password)

imap.select('"INBOX"')

status, message_id_list = imap.search(None, 'ALL')

#convert the string ids to list of email ids
messages = message_id_list[0].split(b' ')





count =1
for mail in messages:
  if messages == [b'']: 
    print("The mailbox is empty")
    break
  
    # mark the mail as deleted
  imap.store(mail, "+FLAGS", "\\Deleted")
  
    
    
   
  print(count,"mail(s) deleted")
  count +=1
  

   
# delete all the selected messages 
imap.expunge()
# close the mailbox
imap.close()

# logout from the account
imap.logout()